### ISSUE TITLE
Code for Derivation of Splicing-Derived Peptides

### ISSUE THREAD

**Issue by amarquard** [ratschlab/pancanatlas_code_public#1]
Thank you for making all this code from your paper available. Although I can't seem to find any available scripts for the part of your methods section named "Derivation of Splicing-Derived Peptides", in order to derive peptide sequences from the neojunctions?

**Comment by mhueser** [comment]
You can now find the code in the <peptide_generation> folder.

**Comment by mhjiang97** [comment]
> You can now find the code in the <peptide_generation> folder.

Hi Mhueser,

I am confused about how to figure out if an alternative splicing in the spladder output files is an annotated one in user-provided gtf. Do you have any idea about this question? If I cannot directly know which alternative splicing event is already annotated from the spladder output files, what should I do to solve it?
Thank you very much! I'm looking forward to your reply~

Best,
Minghao
